sticky-notes/config/routes.rb
Rails.application.routes.draw do
  resources :sections do 
    resources :notes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sticky-notes/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sticky-notes/app/models/note.rb
class Note < ApplicationRecord
  belongs_to :section
end

sticky-notes/app/models/section.rb
class Section < ApplicationRecord
    has_many :notes
    validates :title, presence: true
end

sticky-notes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

sticky-notes/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    # @note = Note.new(note_params)
    @section = Section.find(params[:section_id])
    @note = @section.notes.create(note_params)
    redirect_to sections_path
    # respond_to do |format|
    #   if @note.save
    #     format.html { redirect_to @note, notice: 'Note was successfully created.' }
    #     format.json { render :show, status: :created, location: @note }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @note.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Party!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:content, :due_date, :section_id)
    end
end

sticky-notes/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      # params.fetch(:section, {})
      params.require(:section).permit(:title)
    end
end

sticky-notes/app/helpers/application_helper.rb
module ApplicationHelper
end

sticky-notes/app/helpers/notes_helper.rb
module NotesHelper
end

sticky-notes/app/helpers/sections_helper.rb
module SectionsHelper
end

sticky-notes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StickyNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Righteous|Montserrat|Indie+Flower&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

sticky-notes/app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.datetime_select :due_date %>
  </div>

  <div class="field">
    <%= form.label :section_id %>
    <%= form.text_field :section_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

sticky-notes/app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

sticky-notes/app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Due date</th>
      <th>Section</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.content %></td>
        <td><%= note.due_date %></td>
        <td><%= note.section %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

sticky-notes/app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

sticky-notes/app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @note.due_date %>
</p>

<p>
  <strong>Section:</strong>
  <%= @note.section %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

sticky-notes/app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>

  </div>
<% end %>

sticky-notes/app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Add Note', @section %> |
<%= link_to 'Back', sections_path %>

sticky-notes/app/views/sections/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Righteous|Montserrat|Indie+Flower&display=swap" rel="stylesheet">

<style>
  #board {
    display:flex;
    flex-direction:row;
  }
  #section {
    display: flex;
    flex-direction:column;
    background-color: #fff ;
    padding: 10px ;
    margin-right: 10px;
    min-width:15vw;
    border-radius: 5px;
  }
  #section-header {
    display:flex;
    flex-direction:row;
    border-bottom: 3px solid darkblue;
    line-height:30pt;
    padding:5px;
    justify-content: space-between;
  }
  #section-title {
    font-size:13pt;
    margin-right:5px;
  }
  #closeButton {
    float:right;
    background-color: pink;
    border-radius: 5em;
    height: 20px;
    width:20px;
    text-align:center;
    outline:none;
  }

  .card {
            justify-content: space-around;
            vertical-align: top;
            font-family: 'Indie Flower', cursive;
            font-size: 18pt;
            font-weight: bold;
            margin: 5px 5px;
            padding: 25px;
            width: 150px;
            height: 150px;
            background: #F7E2E1;
            cursor: move;
            text-align: left;
            box-shadow: 2px 2px 2px #707D83;
            resize: none;
            overflow: hidden;
            text-overflow: clip;
        }
  .card:hover {
      box-shadow:10px 10px 7px #707D83);
      -moz-box-shadow:10px 10px 7px #707D83;
      -webkit-box-shadow: 10px 10px 7px #707D83;
      -webkit-transform: scale(1.25);
      -moz-transform: scale(1.25);
      -o-transform: scale(1.25);
      position:relative;
      z-index:5;
      -o-transform:rotate(-3deg);
      -webkit-transform:rotate(-3deg);
      -moz-transform:rotate(-3deg);
      top:-5px;
      background:#F7E9E8;
  }

</style>

<body>

  <p id="notice"><%= notice %></p>

  <h1>Your To-Do List</h1>

  <div id="board">
      <% @sections.each do |section| %>
        <div id = "section">
          <div id = "section-header">
            <div id="section-title"><%= section.title %></div>
            <div><%= link_to 'Add Note', section %></div>
            <div><%= link_to 'Edit', edit_section_path(section) %></div>
            <div><%= link_to raw("<button id = 'closeButton'>x</button>"), section, method: :delete, data: { confirm: 'Are you sure?' } %></div>
            <!-- <div id = 'closeButton'><div> -->
          </div>
          <% section.notes.each do |note| %>
            <div class="card">
              <p>
                <strong><%= note.content %></strong> 
              </p>
              <p>
                <strong>Due:</strong>
                <%= note.due_date %>
              </p>
              <p>
                <%= link_to 'Delete', [note.section, note],
                            method: :delete,
                            data: { confirm: 'Are you sure?' } %>
              </p>
            </div>
          <% end %>
        </div>
      <% end %>
      <%= link_to 'New Section', new_section_path %>
  </div>
</body>

sticky-notes/app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

sticky-notes/app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong><%= @section.title %></strong>
</p>
<h2>Add a Note:</h2>
<%= form_with(model: [ @section, @section.notes.build ], local: true) do |form| %>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
  <p>
    <%= form.label :due_date %><br>
    <%= form.datetime_select :due_date %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

 <%-# link_to 'Edit', edit_section_path(@section) -%>
<%= link_to 'Back', sections_path %>